[package]
name = "homework1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "book"
path = "src/book.rs"

[[bin]]
name = "book2"
path = "src/book2.rs"

[dependencies]
rand = "0.8.5"